build_binary:
     builder: 'particle photon'
     binary_name: 'firmware/target/firmware.bin'
     script: cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/firmware
     
testing:
   pre_flight: echo "....."
   on_success: echo "sssssssssssssssssssssssssssssssssssssssss"
   script: testing/sample-test-script.py
   post_flight: echo "++++++"
   on_failure: echo "fffffffffffffffffffffffffffffffffffffffffffff"
   
   #env_vars:
   #     - $SPN_PARTICLE_TOKEN
   #device_update:
   #    devices:
   #        - $DEVID_1
   #    ota_method: particle
   #    binary: auto
