# build_binary:
#      builder: 'particle photon'
#      binary_name: 'firmware/target/firmware.bin'
#      script: testing/sample-test-script.py
#      pre_flight: echo "++++++"
  
testing:
  pre_flight: "echo ....."
  script: testing/sample-test-script.py
   env_vars:
       - $SPN_PARTICLE_TOKEN
   #device_update:
   #    devices:
   #        - $DEVID_1
   #    ota_method: particle
   #    binary: auto
