build_binary:
    pre_flight: 
        - echo "hello there"
        - cd ../ && echo $PWD
        - sleep 40
    script: echo 'hello there'
    builder: 'particle'
    artifacts:
        -  'testing/'
    post_flight: 
        - echo "finito la musica"

# device_update_intergration:
#   ota_method: spanner shipper
#   env: shipper.yml
#   repos: /kappa/kippo
testing:
    pre_flight: 
        - echo "hello there"
        - cdd ../ && echo $PWD
        - sleep 90
    script: echo 'hello there'
    artifacts:
        -  'testing/'
    post_flight: 
        - echo "finito la musica"
# build_binary:
#     pre_flight:
#        - echo "hello there"

#    env_vars: 
#        - $SPN_PARTICLE_TOKEN
#        ota_method: particle
#        binary: auto#    env_vars: 
#       - $myd
#    device_update:
#      ota_method: 'spanner shipper'
#      env: 'production'
#      repo: 'current'
   #    devices:
   #        - $DEVID_1
   #    ota_method: particle
   #    binary: auto
