build_binary:
     builder: 'particle photon'
     binary_name: st'mo/target/st'mo.bin
     script: cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/st'mo
     pre_flight: echo "++++++"
   
#testing:
#   pre_flight: "echo ....."
#   script: testing/sample-test-script.py
   #env_vars:
   #     - $SPN_PARTICLE_TOKEN
   #device_update:
   #    devices:
   #        - $DEVID_1
   #    ota_method: particle
   #    binary: auto
