# build_binary:
#      builder: 'particle photon'
#      binary_name: 'firmware/target/firmware.bin'
#      script: testing/sample-test-script.py
#      pre_flight: echo "++++++"
# device_update_intergration:
#   ota_method: spanner shipper
#   env: shipper.yml
#   repos: /kappa/kippo
testing:
#   pre_flight: "echo ....."
   script: testing/scenario.py
#   env_vars: 
#       - $SPN_PARTICLE_TOKEN
#    device_update:
#      ota_method: spanner shipper
#      env: prod
#      repo: same
   #    devices:
   #        - $DEVID_1
   #    ota_method: particle
   #    binary: auto
