build_binary:
    pre_flight: 
       - echo "hello there"
       - cd ../ && echo $PWD
    script: echo 'hello there' && cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/app
    post_flight: 
       - echo "finito la musica"
# device_update_intergration:
#   ota_method: spanner shipper
#   env: shipper.yml
#   repos: /kappa/kippo
# testing:
#    script: testing/sample-test-script.py
# build_binary:
#     pre_flight:
#        - echo "hello there"

#    env_vars: 
#        - $SPN_PARTICLE_TOKEN
#        ota_method: particle
#        binary: auto#    env_vars: 
#       - $myd
#    device_update:
#      ota_method: 'spanner shipper'
#      env: 'production'
#      repo: 'current'
   #    devices:
   #        - $DEVID_1
   #    ota_method: particle
   #    binary: auto
