#build_binary:
#     builder: 'particle photon'
#     binary_name: 'firmware/target/firmware.bin'
#     script: cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/firmware

testing:
   script: testing/1.basic-tests/GPIO/read-analog-input.py
   env_vars:
     - $SPN_PARTICLE_TOKEN
   device_update:
       devices:
           - $DEVID_1
       ota_method: particle
       binary: auto
