#build_binary:
#     builder: 'particle photon'
#     binary_name: 'firmware/target/firmware.bin'
#     script: cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/firmware

testing:
   script: testing/2.simple-tests/drive-dig-in-pin-to-trigger-network-cmd.py
    device_update:
        env_vars:
            - $SPN_PARTICLE_TOKEN
        devices:
            - $DEVID_1
        ota_method: particle
        binary: auto
