# build_binary:
#      builder: 'particle photon'
#      binary_name: 'firmware/target/firmware.bin'
#      script: testing/sample-test-script.py
#      pre_flight: echo "++++++"
# device_update_intergration:
#   ota_method: spanner shipper
#   env: shipper.yml
#   repos: /kappa/kippo
testing:
    device_update:
        devices:
            - $my
        ota_method: particle
        binary: auto
#    env_vars: 
#       - $myd
#    device_update:
#      ota_method: 'spanner shipper'
#      env: 'production'
#      repo: 'current'
   #    devices:
   #        - $DEVID_1
   #    ota_method: particle
   #    binary: auto
